# Generated by Django 2.2 on 2019-04-22 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_author',
        ),
    ]
