# Generated by Django 2.1.7 on 2019-04-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField()),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
