# Generated by Django 2.1.7 on 2019-04-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190323_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
